import { useState } from 'react'
import { MIST_BOUNDARY_TOKENS, MIST_GUIDE_VERSION, MIST_IA_MAP, MIST_RELEASE_CHECKS, MIST_RULES } from '../mist-system-contract'
import ThemeSystemHeader from './ThemeSystemHeader'

const views = { mobile: ['Mobile', 390, '20px gutter · 1 column'], tablet: ['Tablet', 768, '32px gutter · 6 columns'], desktop: ['Desktop', 1280, '64px gutter · 12 columns'] }
const palette = [['Paper','#fbfbf8','기본 종이'],['Ink','#292824','제목'],['Body','#59574f','본문'],['Meta','#77746c','보조 정보'],['Taupe','#786f58','행동·현재'],['Project','#eee1a4','프로젝트 면'],['Selection','#ded7c4','텍스트 선택']]
const rules = MIST_RULES
const map = MIST_IA_MAP
const cursorMarks = ['clover','spark','ring','cross']
const randomCursorMark = cursorMarks[Math.floor(Math.random() * cursorMarks.length)]
const releaseChecks = MIST_RELEASE_CHECKS
const Block = ({n,title,note,children}) => <section className="fds-block"><header><span>{n}</span><div><h2>{title}</h2><p>{note}</p></div></header>{children}</section>

export default function FrontDesignSystem() {
  const [view,setView] = useState('mobile'); const [surface,setSurface] = useState('paper'); const [label,width,note] = views[view]
  return <main className="fds-page"><ThemeSystemHeader themeId="mist" eyebrow={`MIST THEME / SYSTEM v${MIST_GUIDE_VERSION}`} title="Portfolio Front Design System"/><div className="fds-wrap">
    <section className="fds-intro"><div><span>SINGLE SOURCE OF TRUTH · v{MIST_GUIDE_VERSION}</span><h1>현재 포트폴리오의<br/>시각 언어와 UX 규칙</h1></div><p>흰 종이 위에 편집된 인쇄물의 리듬을 유지합니다. 화면 크기가 달라져도 정보의 순서와 시작선은 바뀌지 않습니다.</p></section>
    <Block n="01" title="Foundation" note="종이, 잉크, 타이포그래피와 간격"><div className="fds-colors">{palette.map(([a,b,c])=><article key={a}><i style={{background:b}}/><b>{a}</b><code>{b}</code><p>{c}</p></article>)}</div><div className="fds-foundation"><article><span>DISPLAY TYPE</span><div className="fds-type-pair"><h3>Selected Work</h3><h3 className="fds-ko-title">사용자와 비즈니스의 균형</h3></div><p>영문 표제는 Newsreader, 한글 제목은 Gowun Batang을 명시적으로 사용합니다.</p></article><article><span>SPACING TOKENS</span><dl className="fds-spacing-list"><div><dt>8px</dt><dd>아이콘·텍스트 사이</dd></div><div><dt>16px</dt><dd>한 항목 내부</dd></div><div><dt>24px</dt><dd>카드 내부 여백</dd></div><div><dt>40px</dt><dd>콘텐츠 그룹 사이</dd></div><div><dt>64px</dt><dd>섹션 사이</dd></div></dl><p>간격은 사용처에 따라 고정하며 임의 값을 추가하지 않습니다.</p></article><article><span>INK & HIGHLIGHT</span><dl className="fds-ink-list">{MIST_BOUNDARY_TOKENS.map(([name,value,note])=><div key={name}><dt>{name}</dt><dd><b>{value}</b><small>{note}</small></dd></div>)}<div><dt>Selection</dt><dd><b>#ded7c4</b><small>텍스트 선택과 지정된 면 강조에만 사용</small></dd></div></dl><p>강조는 잉크 농도와 지정된 면색만 사용합니다.</p></article></div></Block>
    <Block n="01A" title="Alignment & hierarchy" note="기계적 좌표보다 반복되는 시각 기준선을 우선"><div className="fds-alignment-grid"><article><span>PAGE GRID</span><dl><div><dt>Desktop</dt><dd>12 columns · 64px gutter</dd></div><div><dt>Tablet</dt><dd>6 columns · 32px gutter</dd></div><div><dt>Mobile</dt><dd>4 columns · 20px gutter</dd></div></dl></article><article><span>ROW GRID</span><div className="fds-alignment-row"><small>01</small><b>2023</b><strong>Lumen Labs</strong></div><p>번호 40px · 연도 120px · 내용 유동. 연도는 제목이 아닌 메타 정보로 고정합니다.</p></article><article><span>OPTICAL ALIGNMENT</span><dl><div><dt>Mono</dt><dd>11px / 20px</dd></div><div><dt>Title</dt><dd>15px / 20px</dd></div><div><dt>Row</dt><dd>32px line box</dd></div><div><dt>Multiline</dt><dd>첫 줄 상단 · index +3px</dd></div></dl><p>연도 크기를 문맥마다 바꾸지 않고, 회사명·항목명만 주제목으로 올립니다.</p></article></div><div className="fds-date-table"><header><span>CONTEXT</span><span>DATE</span><span>PRIMARY</span><span>RULE</span></header><div><b>Experience</b><time>2023.03 ~</time><strong>Lumen Labs</strong><p>날짜는 메타, 회사명이 주제목</p></div><div><b>Journey</b><time>2023</time><strong>Lumen Labs</strong><p>연도는 메타, 회사명이 주제목</p></div><div><b>Activity</b><time>2025</time><strong className="fds-ko-title">발표</strong><p>연도는 메타, 활동 유형이 주제목</p></div></div><div className="fds-box-rhythm"><header><span>BOX VERTICAL RHYTHM</span><p>행 높이는 가장 긴 콘텐츠가 결정합니다.</p></header><div><article><small>COMPARISON CELL</small><strong>내용 묶음 중앙</strong><p>짧은 셀도 같은 행 중앙에 위치</p></article><article><small>CONTENT CARD</small><strong>상단 정렬</strong><p>상하 24px 대칭 padding</p></article><article><small>LIST ROW</small><strong>상·하선 한 세트</strong><p>첫 줄 기준 · 상하 20px 대칭 padding</p></article></div></div></Block>
    <Block n="02" title="Component language" note="이름, 실제 표본, 사용 규칙을 분리한 프론트 반복 문법"><div className="fds-patterns">
      <article><span>SECTION HEADING</span><div className="fds-section-heading"><small>PROJECTS</small><h3>Featured Projects</h3></div><p>상단 영문은 섹션 분류, 큰 제목은 실제 섹션명입니다.</p></article>
      <article className="is-project"><span>PROJECT SURFACE</span><div className="fds-project-surface"><small>AI PRODUCT</small><h3>LLM 고객 상담 어시스턴트</h3><button>VIEW PROJECT ↗</button></div><p>화살표는 이동 가능한 행동에만 붙입니다.</p></article>
      <article><span>INDEX ROW</span><div className="fds-index-sample"><small>01</small><b>2023</b><strong>Lumen Labs</strong></div><p>번호·연도·제목은 하나의 기준선과 고정 열을 사용합니다.</p></article>
      <article><span>TEXT ACTION</span><div className="fds-action-sample"><button>VIEW PROJECT <i aria-hidden="true">↗</i></button><small>MIN. 44PX</small></div><p>밑줄과 방향 기호로 이동을 표현하며 크기는 변하지 않습니다.</p></article>
    </div></Block>
    <Block n="02A" title="Front components" note="공개 화면에서 실제로 사용하는 모든 표현 단위"><div className="fds-library">
      <article className="is-hero"><span>HERO</span><div className="fds-fog"/><h3>PORTFOLIO</h3><p>무채색 구름형 렌즈 블러 · 3개 층이 화면 폭을 서로 다른 속도로 순회 · 모든 글자 판독</p></article>
      <article><span>STATS</span><div className="fds-stat"><small>01</small><b>YEARS EXPERIENCE</b><i/><strong>8+</strong></div><div className="fds-stat"><small>02</small><b>PROJECTS</b><i/><strong>9+</strong></div><div className="fds-stat"><small>03</small><b>COMPANIES</b><i/><strong>3</strong></div></article>
      <article><span>ABOUT</span><h3>Designing the balance between users and business</h3><p>명시적 줄바꿈 우선 · 본문 15px 이상</p></article>
      <article className="is-project"><span>PROJECT CASE</span><small>AI PRODUCT</small><h3>LLM 고객 상담 어시스턴트</h3><div className="fds-metrics"><b>-42%<small>처리 시간</small></b><b>4.6<small>CSAT</small></b><b>9주<small>MVP 출시</small></b></div></article>
      <article><span>EXPERIENCE</span><div className="fds-row"><small>01</small><div><b className="fds-date">2023.03 ~</b><h4>Lumen Labs</h4><p>Senior Product Manager</p></div></div><p>날짜는 메타, 회사명은 주제목. 행마다 동일한 상하 패딩과 시작선을 사용합니다.</p></article>
      <article><span>JOURNEY</span><div className="fds-row fds-row--journey"><small>03</small><b>2023</b><h4>Lumen Labs <em>✦ NOW</em></h4></div><p>연도는 독립 메타 열로 유지합니다. 현재 상태는 회사명 뒤에 붙이고 행 높이를 늘리지 않습니다.</p></article>
      <article><span>ACHIEVEMENT</span><div className="fds-row"><small>01</small><div><h4 className="fds-ko-title">AI 상담 어시스턴트 출시</h4><p>상담 처리 시간 -42%, CSAT 4.6/5.0</p></div></div><p>번호 다음의 모든 제목과 본문은 같은 시작선에 맞춥니다.</p></article>
      <article><span>BACKGROUND</span><div className="fds-row"><small>01</small><div><h4>Education</h4><p>한빛대학교 · 경영학·컴퓨터과학</p></div></div><div className="fds-row"><small>02</small><div><h4>Activities</h4><p>연도 · 유형 · 제목 · 설명</p></div></div></article>
      <article><span>PROJECT DETAIL</span><div className="fds-brief"><b>Brief</b><p>도입 설명은 번호형 본문과 구분되는 종이 띠로 표시합니다.</p></div><div className="fds-gallery">3 : 2 IMAGE</div><p>Close · Previous · All · Next · 공통 Footer</p></article>
      <article><span>ACCESS GATE</span><div className="fds-gate"><small>PM PORTFOLIO</small><h3>Data-driven decisions,<br/>User-centric design</h3><div className="fds-gate__form"><input aria-label="Access token example" placeholder="Enter access token" readOnly/><button>VIEW PORTFOLIO</button></div></div><p>데스크톱은 두 열, 모바일은 소개 다음 48px 이후 인증 패널이 시작됩니다.</p></article>
      <article className="is-wide"><span>SESSION / ACCESS</span><div className="fds-session-warning" role="status"><div><small>ACCESS EXPIRING</small><b>접속 만료까지 05:00</b><p>작업을 마치거나 접근 시간을 연장해 주세요.</p></div><button>DISMISS</button></div><div className="fds-session-stage"><div className="fds-session-blocker" role="alert"><div><small>ACCESS EXPIRED</small><b>접속 시간이 만료되었습니다</b><p>포트폴리오는 즉시 숨겨집니다. 계속 보려면 다시 인증해 주세요.</p><button>RE-AUTHENTICATE →</button></div></div></div><p>만료 임박 경고만 비차단으로 알립니다. 만료 시 포트폴리오를 언마운트하고 불투명한 전체 화면 재인증 게이트로 즉시 교체합니다.</p></article>
      <article><span>SECTION RAIL</span><div className="fds-rail-demo"><div className="fds-rail"><i/><i/><i className="is-near"/><i className="is-current"/><i className="is-near"/><i/><i/></div><div className="fds-rail-card"><b>Portfolio</b><small>제품의 문제를 정의하고 결과까지 연결한 작업들</small></div></div><p>툴팁은 선택한 눈금 오른쪽의 사용 가능한 폭을 우선 사용합니다. 충분한 폭에서 단어를 임의로 꺾지 않습니다.</p></article>
      <article><span>SKILL TAGS</span><div className="fds-skill-tags"><span>Product Strategy</span><span>Data Analysis</span><span>AI/ML Product</span></div><p>분류 데이터와 관계없이 화면은 동일한 단색 잉크·면·선만 사용합니다.</p></article>
      <article><span>ARCHIVE CARD</span><div className="fds-archive-card"><div className="fds-gallery">PROJECT IMAGE</div><div><small>01</small><h4>NOMA Product Launch</h4><p>Integrated campaign · 2026</p></div></div></article>
      <article><span>MULTI-IMAGE GALLERY</span><div className="fds-gallery">ACTIVE IMAGE · 01</div><div className="fds-gallery-controls"><b>01 / 03</b><button>PREVIOUS</button><button>NEXT</button></div><div className="fds-gallery-thumbs"><button aria-current="true">01</button><button>02</button><button>03</button></div><p>저장 순서를 따르며 버튼·썸네일·모바일 스와이프로 넘깁니다. 전환 중에도 3:2 무대 높이는 유지합니다.</p></article>
      <article><span>PROJECT NAVIGATION</span><div className="fds-project-nav"><button><small>PREVIOUS</small><b>NOMA</b></button><button><small>ALL</small><b>PROJECTS</b></button><button><small>NEXT</small><b>STILL</b></button></div><p>세 칸의 너비와 기준선을 고정합니다.</p></article>
      <article><span>UTILITY ACTIONS</span><div className="fds-utility"><button className="fds-close-sample" aria-label="Close example">CLOSE <i aria-hidden="true">×</i></button><button className="fds-top-sample">BACK TO TOP ↑</button></div><p>Close는 상세 우측 상단에 고정합니다. Floating Top은 35vh 이후 우측 하단에 표시하고 Footer 120px 전부터 숨깁니다. Footer의 Back to top은 독립 행에 유지합니다.</p></article>
      <article className="is-wide"><span>FOOTER</span><div className="fds-footer"><p>© 2026. JIYUN. ALL RIGHTS RESERVED.</p><div><p>INTERESTED IN WORKING TOGETHER? LET'S CONNECT.</p><div className="fds-footer__contacts"><b>HELLO@EXAMPLE.COM</b><b>LINKEDIN ↗</b></div></div><strong>BACK TO TOP ↑</strong></div><p>모바일은 안내, Back to top, 저작권을 독립 행으로 배치합니다. 플로팅 Top은 푸터 120px 전에 숨깁니다.</p></article>
      <article><span>ORNAMENT MOTION</span><div className="fds-symbols"><div><i className="is-star">✦</i><small>SPIN · 9S</small></div><div><i className="is-cross">×</i><small>REVERSE · 12S</small></div><div><i className="is-dot">••</i><small>DRIFT · 5.5S</small></div><div><i className="is-clover">+</i><small>STEPS · 7S</small></div></div><p>CSS 기하학 기호만 사용합니다. 콘텐츠와 겹치지 않으며 reduced-motion에서는 모두 정지합니다.</p></article>
      <article><span>PAGE / SCROLL EFFECT</span><dl className="fds-motion-list"><div><dt>PAGE</dt><dd>OPTIONAL · 종이 면 220ms crossfade. 이동 방향을 흉내 내는 slide 금지</dd></div><div><dt>SCROLL</dt><dd>고정 종이 배경과 독립 포그만 유지. parallax·카드 이동·섹션 들썩임 금지</dd></div><div><dt>FOG</dt><dd>3개 이상의 합집합 구름층이 가로 16~78%를 21~38초 주기로 교차 순회. 흰 면·역마스크·글자 절단·중앙 고정 금지</dd></div><div><dt>REDUCED</dt><dd>포그와 장식 정지, 페이지는 즉시 전환</dd></div></dl><p>효과는 Mist의 종이와 안개 개념을 설명할 때만 사용하고 읽기 속도보다 앞서지 않습니다.</p></article>
      <article><span>CURSOR / HOVER</span><div className="fds-cursor-pool"><b>RANDOM POOL</b>{cursorMarks.map(mark=><i key={mark} className={`fds-cursor-mark is-${mark}`} title={mark}/>)}</div><div className="fds-cursor-states"><div className="fds-cursor-demo fds-cursor-demo--default"><i className={`fds-cursor-mark is-${randomCursorMark}`}/><b>DEFAULT FOLLOWER</b></div><div className="fds-cursor-demo fds-cursor-demo--action"><b>PROJECT CARD</b><em>CASE NOTE ↗</em></div><div className="fds-cursor-demo fds-cursor-demo--action"><b>ACHIEVEMENT</b><em>VIEW NOTE ↓</em></div></div><dl className="fds-motion-list"><div><dt>POINTER</dt><dd>시스템 화살표·손가락 커서를 항상 유지해 실제 조준점을 보존</dd></div><div><dt>RELOAD</dt><dd>브라우저 새로고침마다 clover · spark · ring · cross 중 하나를 다시 선택</dd></div><div><dt>FOLLOW</dt><dd>실제 포인터 우하단 14px에 13px 보조 기호를 배치하고 2.8초 steps(20) 회전</dd></div><div><dt>LABEL</dt><dd>등록된 행동 요소에서는 보조 기호를 숨기고 실제 목적 라벨만 표시</dd></div><div><dt>TOUCH</dt><dd>보조 표시 숨김 · 기본 터치 동작 유지</dd></div></dl></article>
      <article><span>INTERACTION STATES</span><div className="fds-state-demo"><div><small>DEFAULT</small><button>VIEW PROJECT ↗</button></div><div><small>KEYBOARD FOCUS</small><button className="is-focus">VIEW PROJECT ↗</button></div></div><p>Hover·Focus·Pressed에서 위치와 크기는 바뀌지 않습니다.</p></article>
      <article><span>EMPTY STATE</span><div className="fds-message"><small>NO PROJECTS YET</small><b>표시할 프로젝트가 없습니다</b><p>프로젝트가 등록되면 이 위치에 최신 작업부터 표시됩니다.</p><button>VIEW ALL SECTIONS →</button></div><dl className="fds-empty-variants"><div><dt>PROJECTS</dt><dd>다른 섹션 보기</dd></div><div><dt>SEARCH</dt><dd>필터 초기화</dd></div><div><dt>GALLERY</dt><dd>프로젝트 설명 유지</dd></div><div><dt>SELECTION</dt><dd>첫 항목 선택 안내</dd></div></dl></article>
      <article><span>ERROR STATE</span><div className="fds-message"><small>CONTENT UNAVAILABLE</small><b>프로젝트를 불러오지 못했습니다</b><p>원인을 짧게 설명하고 이전의 안전한 화면으로 돌아갈 수 있어야 합니다.</p><button>RETURN TO ARCHIVE →</button></div></article>
    </div></Block>
    <Block n="03" title="UX contract" note="반복 설명을 없애는 Do / Don't"><div className="fds-rules">{rules.map(([a,b,c],i)=><article key={a}><header><span>{String(i+1).padStart(2,'0')}</span><h3>{a}</h3></header><div><b>DO</b><p>{b}</p></div><div><b>DON'T</b><p>{c}</p></div></article>)}</div></Block>
    <Block n="04" title="Information architecture" note="공개 포트폴리오의 페이지와 이동"><div className="fds-ia">{map.map(([a,items])=><article key={a}><header>{a}</header><ol>{items.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</li>)}</ol></article>)}</div><p className="fds-contract">상세 페이지는 Close로 홈에 복귀하고 아카이브·상세는 공통 푸터를 사용합니다. 화살표와 링크는 실제 목적지를 가져야 합니다.</p></Block>
    <Block n="05" title="Responsive preview" note="동일 패턴의 모바일·태블릿·데스크톱 비교"><div className="fds-tools"><div>{Object.entries(views).map(([k,v])=><button key={k} aria-pressed={view===k} onClick={()=>setView(k)}>{v[0]} <span>{v[1]}px</span></button>)}</div><div><button aria-pressed={surface==='paper'} onClick={()=>setSurface('paper')}>Paper</button><button aria-pressed={surface==='project'} onClick={()=>setSurface('project')}>Project</button></div></div><div className="fds-stage"><div className={`fds-preview is-${view} is-${surface}`} style={{'--frame-width':`${width}px`}}><header><span>PORTFOLIO</span><b>{label}</b></header><main><small>PROJECTS / 03</small><h3>Selected Work</h3><div className="fds-demo-grid"><aside><span>01</span><b>NOMA Product Launch</b><small>Campaign · 2026</small></aside><section><div className="fds-demo-image"/><h4>Clear hierarchy,<br/>stable rhythm.</h4><p>화면이 달라져도 제목, 본문, 메타, 행동의 역할과 순서를 유지합니다.</p><button>VIEW PROJECT ↗</button></section></div></main><footer>{note}</footer></div></div></Block>
    <Block n="06" title="Release gate" note="한 항목이라도 실패하면 테마를 배포하지 않습니다"><div className="fds-release-gate">{releaseChecks.map(([title,items],groupIndex)=><article key={title}><header><span>{String(groupIndex+1).padStart(2,'0')}</span><h3>{title}</h3></header><ol>{items.map((item,itemIndex)=><li key={item}><span>{String(itemIndex+1).padStart(2,'0')}</span><p>{item}</p><b>REQUIRED</b></li>)}</ol></article>)}</div></Block>
  </div></main>
}
