import { useState } from 'react'

const views = { mobile: ['Mobile', 390, '20px gutter · 1 column'], tablet: ['Tablet', 768, '32px gutter · 6 columns'], desktop: ['Desktop', 1280, '64px gutter · 12 columns'] }
const palette = [['Paper','#fbfbf8','기본 종이'],['Ink','#292824','제목'],['Body','#59574f','본문'],['Meta','#77746c','보조 정보'],['Taupe','#786f58','행동·현재'],['Project','#eee1a4','프로젝트 면']]
const rules = [['정렬','공통 컨테이너와 시작선','섹션별 임의 여백'],['줄바꿈','저장된 개행 우선','넓은 화면 강제 개행'],['간격','8px 배수와 대칭 패딩','임의 margin'],['색상','역할과 배경으로 결정','섹션별 새 색'],['상태','색과 선으로 표현','크기·위치 변화'],['콘텐츠','원문과 순서 보존','스타일을 위한 삭제']]
const map = [['ENTRY',['Access Gate','Portfolio Home']],['HOME',['Hero','About','Featured Projects','Work Experience','Career Journey','Achievements','Background','Footer']],['PROJECT',['Selected Work','All Projects','Project Detail','Image Gallery','Previous / All / Next']]]
const Block = ({n,title,note,children}) => <section className="fds-block"><header><span>{n}</span><div><h2>{title}</h2><p>{note}</p></div></header>{children}</section>

export default function FrontDesignSystem({ onBack }) {
  const [view,setView] = useState('mobile'); const [surface,setSurface] = useState('paper'); const [label,width,note] = views[view]
  return <main className="fds-page"><header className="fds-topbar"><div><span>MIST THEME / SYSTEM v1.0</span><strong>Portfolio Front Design System</strong></div><button onClick={onBack}>검토 종료 ×</button></header><div className="fds-wrap">
    <section className="fds-intro"><div><span>SINGLE SOURCE OF TRUTH</span><h1>현재 포트폴리오의<br/>시각 언어와 UX 규칙</h1></div><p>흰 종이 위에 편집된 인쇄물의 리듬을 유지합니다. 화면 크기가 달라져도 정보의 순서와 시작선은 바뀌지 않습니다.</p></section>
    <Block n="01" title="Foundation" note="종이, 잉크, 타이포그래피와 간격"><div className="fds-colors">{palette.map(([a,b,c])=><article key={a}><i style={{background:b}}/><b>{a}</b><code>{b}</code><p>{c}</p></article>)}</div><div className="fds-foundation"><article><span>DISPLAY</span><h3>Selected Design Work</h3><p>영문 표제는 Editorial serif, 한국어 본문은 Gowun Batang.</p></article><article><span>SPACING</span><div className="fds-scale"><i>8</i><i>16</i><i>24</i><i>40</i><i>64</i></div><p>새 값보다 기존 토큰을 우선합니다.</p></article><article><span>RULES</span><b>Strong 50%</b><b>Row 28%</b><b>Soft 18%</b><p>같은 면에서는 잉크색 하나에 투명도만 적용합니다.</p></article></div></Block>
    <Block n="02" title="Component language" note="프론트의 반복 표현 문법"><div className="fds-patterns"><article><span>SECTION HEADER</span><small>PROJECTS</small><h3>Featured Projects</h3><p>라벨 → 제목 → 설명</p></article><article className="is-project"><span>PROJECT SURFACE</span><h3>AI Product ↘</h3><p>노란 면에 차가운 회색 금지</p></article><article><span>INDEX ROW</span><div><small>01</small><b>2023</b><strong>Lumen Labs</strong></div><p>번호·연도·제목 열 고정</p></article><article><span>ACTION</span><button>VIEW PROJECT ↗</button><p>44px 이상, 실제 목적지 필수</p></article></div></Block>
    <Block n="03" title="UX contract" note="반복 설명을 없애는 Do / Don't"><div className="fds-rules">{rules.map(([a,b,c],i)=><article key={a}><span>{String(i+1).padStart(2,'0')}</span><h3>{a}</h3><div><b>DO</b><p>{b}</p></div><div><b>DON'T</b><p>{c}</p></div></article>)}</div></Block>
    <Block n="04" title="Information architecture" note="공개 포트폴리오의 페이지와 이동"><div className="fds-ia">{map.map(([a,items])=><article key={a}><header>{a}</header><ol>{items.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</li>)}</ol></article>)}</div><p className="fds-contract">상세 페이지는 Close로 홈에 복귀하고 아카이브·상세는 공통 푸터를 사용합니다. 화살표와 링크는 실제 목적지를 가져야 합니다.</p></Block>
    <Block n="05" title="Responsive preview" note="동일 패턴의 모바일·태블릿·데스크톱 비교"><div className="fds-tools"><div>{Object.entries(views).map(([k,v])=><button key={k} aria-pressed={view===k} onClick={()=>setView(k)}>{v[0]} <span>{v[1]}px</span></button>)}</div><div><button aria-pressed={surface==='paper'} onClick={()=>setSurface('paper')}>Paper</button><button aria-pressed={surface==='project'} onClick={()=>setSurface('project')}>Project</button></div></div><div className="fds-stage"><div className={`fds-preview is-${view} is-${surface}`} style={{'--frame-width':`${width}px`}}><header><span>PM PORTFOLIO</span><b>{label}</b></header><main><small>PROJECTS / 03</small><h3>Selected Design Work</h3><div className="fds-demo-grid"><aside><span>01</span><b>NOMA Product Launch</b><small>Campaign · 2026</small></aside><section><div className="fds-demo-image"/><h4>Clear hierarchy,<br/>stable rhythm.</h4><p>화면이 달라져도 제목, 본문, 메타, 행동의 역할과 순서를 유지합니다.</p><button>VIEW PROJECT ↗</button></section></div></main><footer>{note}</footer></div></div></Block>
    <Block n="06" title="Release checklist" note="프론트 변경 전 고정 검수"><ol className="fds-checklist"><li>320·360·390·430px 가로 스크롤 없음</li><li>768·1024px 시작선과 열 유지</li><li>1280·1440px 불필요한 제목 개행 없음</li><li>본문 15px·메타 12px·터치 44px 이상</li><li>장식 겹침 없음·reduced-motion 지원</li><li>원문·줄바꿈·링크 목적지 보존</li></ol></Block>
  </div></main>
}
